server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/library_catalog}
      auto-index-creation: true

jwt:
  secret: ${JWT_SECRET:libSecretKey2024LibraryAppSecretKey256Bits!}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.library.catalog: DEBUG
